# Generated by Django 4.2.3 on 2023-08-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=45, null=True, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('job', models.IntegerField(null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('password', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
