# Generated by Django 4.2.3 on 2023-08-20 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('chat_date', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('student', '학생'), ('chatbot', '챗봇')], max_length=30)),
                ('message_text', models.TextField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllDialogue',
            fields=[
                ('dialogue_id', models.AutoField(primary_key=True, serialize=False)),
                ('dialogue_text', models.TextField()),
                ('chat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultResult',
            fields=[
                ('result_time', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ImageField(null=True, upload_to='')),
                ('emotion_temp', models.FloatField()),
                ('summary', models.TextField()),
                ('emotion_list', models.JSONField()),
                ('want_consult', models.BooleanField()),
                ('chat_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.chatroom')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
